config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pdf-generator', to: 'pages#pdf_generator', as: :pdf_generator
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def pdf_generator
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html
      format.pdf do
        render  pdf: "file_name",
                layout: 'pdf.html.erb'
                # Excluding ".pdf" extension.
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta data -->
    <title>App name</title>
    <meta name="Language" content="fr" />
    <meta name="description" content="app description">

    <!-- csrf & csp -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- import CSS & JS files -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- notices & alerts -->
    <%= render 'shared/flashes' %>

    <!-- navbar -->
    <%= render 'shared/navbar' %>

    <!-- main content -->
    <main role="main">
      <%= yield %>
    </main>

    <!-- footer -->
    <%= render 'shared/footer' %>

    <!-- noscript tag when JS brower is OFF -->
    <noscript>Votre navigateur web a bloqué le JavaScript. C'est important de le débloquer pour profiter de toutes les fonctionnallités de ce site web !</noscript>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag 'application', media: 'all' %>
    <%= wicked_pdf_javascript_include_tag wicked_pdf_asset_pack_path("application.js") %>
  </head>
  <body>
    <div id="header">
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1>Pages#home</h1>
</div>

app/views/pages/pdf_generator.html.erb
<div class="container my-5">
  <h1 class="text-center">All restaurants</h1>
  <h2 class="text-left">List of restaurants</h2>
  <%= link_to "Generate test PDF", pdf_generator_path(format: :pdf), target: "_blank", rel: "noopener noreferer", class: "btn btn-primary my-3" %>

  <table class="table table-hover table-responsive text-center">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Food type</th>
        <th scope="col">Address</th>
        <th scope="col">Rating</th>
      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td>
            <%= restaurant.name %>
          </td>
          <td>
            <%= restaurant.food_type %>
          </td>
          <td>
            <%= restaurant.address %>
          </td>
          <td>
            <%= restaurant.rating %>
          </td>
        </tr>
      <% end%>
    </tbody>
  </table>

</div>

app/views/pages/pdf_generator.pdf.erb
<div class="container my-5">
  <h1 class="text-center">All restaurants</h1>
  <h2 class="text-left">List of restaurants</h2>

  <table class="table table-hover table-responsive text-center" style="width:100%">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Food type</th>
        <th scope="col">Address</th>
        <th scope="col">Rating</th>
      </tr>
    </thead>
    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td>
            <%= restaurant.name %>
          </td>
          <td>
            <%= restaurant.food_type %>
          </td>
          <td>
            <%= restaurant.address %>
          </td>
          <td>
            <%= restaurant.rating %>
          </td>
        </tr>
      <% end%>
    </tbody>
  </table>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="status">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer role="contentinfo" aria-label="pied de page" id="footer" class="bg-dark text-white">
  <div class="container mt-1">
    <div class="row align-items-center justify-content-between">

      <!-- icons réseaux sociaux -->
      <div class="col-12 col-lg-3 text-center text-lg-left mb-4" aria-label="liens vers nos réseaux sociaux">
        <a href="https://www.facebook.com" target="_blank" rel="noopener noreferrer" title="compte Facebook" aria-label="page facebook"><i class="fab fa-facebook"></i></a>
        <a href="https://www.instagram.com" target="_blank" rel="noopener noreferrer" title="compte Instagram" aria-label="compte Instagram"><i class="fab fa-instagram"></i></a>
      </div>

      <!-- CGV & contact -->
      <address class="col-12 col-lg-9 d-flex flex-column flex-md-row justify-content-around text-center">
        <p><%= link_to 'Conditions Générales de Vente', '#', class: "text-decoration-none text-14", target: "_blank", rel: "noopener noreferrer" %></p>
        <p><%= link_to 'Contactez-nous', '#', class: "text-decoration-none text-14", target: "_blank", rel: "noopener noreferrer" %></p>
        <p class="text-14" aria-label="addresse mail de contact">contact@mondomaine.fr</p>
      </address>

    </div>
  </div>

  <!-- copyright -->
  <div class="bg-black text-center">
    <div class="container d-flex flex-column flex-lg-row justify-content-between align-items-center">
      <small class="font-weight-bold text-center my-2">Tous droits réservés | MONDOMAINE 2021</small>
      <small class="mb-2 mb-lg-0 web-developer" aria-label="créateur du site"><em>Site créé par <a href="https://bertrand-bichat.github.io/" class="text-primary text-decoration-none" target="_blank" rel="noopener noreferrer author" title="créateur du site">Bertrand Bichat</a></em></small>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <nav role="navigation" aria-label="menu principale de navigation" class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom border-dark">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", alt: 'logo', loading: 'lazy' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Afficher le menu de navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "PDF restaurants list", pdf_generator_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", alt: 'paramètres', loading: 'lazy', data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, aria: { label: 'paramètres' } %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>